# Generated by Django 6.0.3 on 2026-03-26 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Ягода')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='клиент')),
                ('phone', models.CharField(max_length=12, verbose_name='клиент')),
                ('address', models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес квартиры')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Декор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Надпись')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество слоев')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=32, verbose_name='Форма коржа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Топпинг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='название торта')),
                ('description', models.TextField(blank=True, verbose_name='описание торта')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение торта')),
                ('default', models.BooleanField(default=False, verbose_name='торт в ассортименте')),
                ('berries', models.ManyToManyField(related_name='cakes', to='BakeCake.berry', verbose_name='ягоды')),
                ('decor', models.ManyToManyField(related_name='cakes', to='BakeCake.decor', verbose_name='декор')),
                ('inscription', models.ManyToManyField(related_name='cakes', to='BakeCake.inscription', verbose_name='надпись')),
                ('layers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='BakeCake.layer', verbose_name='слои')),
                ('shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='BakeCake.shape', verbose_name='форма')),
                ('toppings', models.ManyToManyField(related_name='cakes', to='BakeCake.topping', verbose_name='топинги')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма заказа')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='BakeCake.client', verbose_name='клиент')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество тортов')),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_cakes', to='BakeCake.cake', verbose_name='торты')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_cakes', to='BakeCake.order', verbose_name='заказы')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(related_name='orders', through='BakeCake.OrderedCake', to='BakeCake.cake', verbose_name='торты'),
        ),
    ]
