# Generated by Django 5.2.12 on 2026-03-27 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0002_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berry',
            options={'ordering': ('id',), 'verbose_name': 'Ягоды', 'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('id',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'ordering': ('id',), 'verbose_name': 'Декор', 'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ('id',), 'verbose_name': 'Надпись', 'verbose_name_plural': 'Надписи'},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ('quantity',), 'verbose_name': 'Количество уровней', 'verbose_name_plural': 'Количество уровней'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('order_time',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ('id',), 'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ('id',), 'verbose_name': 'Топпинг', 'verbose_name_plural': 'Топпинг'},
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='berry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='decor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderedcake',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
