# Generated by Django 5.2.12 on 2026-03-27 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0003_alter_berry_options_alter_cake_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Промокод')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('discount_percent', models.PositiveIntegerField(help_text='От 1 до 100', verbose_name='Процент скидки')),
                ('valid_from', models.DateTimeField(verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(verbose_name='Окончание действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Количество применений')),
                ('users_who_used', models.ManyToManyField(blank=True, related_name='promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Использовавшие пользователи')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BakeCake.promocode', verbose_name='Промокод'),
        ),
    ]
