# Generated by Django 5.2.12 on 2026-03-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0004_client_email'),
        ('BakeCake', '0005_alter_order_options_order_address_and_more'),
    ]

    operations = [
    ]
